export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './companyCo2YearlyController.service';
import { CompanyCo2YearlyControllerService } from './companyCo2YearlyController.service';
export * from './companyController.service';
import { CompanyControllerService } from './companyController.service';
export * from './coordinateController.service';
import { CoordinateControllerService } from './coordinateController.service';
export * from './landController.service';
import { LandControllerService } from './landController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './treeController.service';
import { TreeControllerService } from './treeController.service';
export * from './uploadsController.service';
import { UploadsControllerService } from './uploadsController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, CompanyCo2YearlyControllerService, CompanyControllerService, CoordinateControllerService, LandControllerService, PingControllerService, TreeControllerService, UploadsControllerService, UserControllerService];
