steps:
  # 1️⃣ Limpiar dist y instalar dependencias
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        rm -rf dist/
        npm install

  # 2️⃣ Build Angular producción usando script centralizado
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build:prod

  # 3️⃣ Subir solo el contenido de browser/ al bucket raíz
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - '-m'
      - 'rsync'
      - '-r'
      - '-c'
      - '-d'
      - 'dist/forest-plus/browser/'   # <-- contenido de browser al raíz del bucket
      - 'gs://forestplus-angular-frontend'

  # 4️⃣ Forzar permisos públicos
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - '-m'
      - 'acl'
      - 'ch'
      - '-r'
      - '-u'
      - 'AllUsers:R'
      - 'gs://forestplus-angular-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
