/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponse';


/**
 * Respuesta de autenticación con token y datos del usuario
 */
export interface AuthResponseDto { 
    /**
     * Token JWT del usuario
     */
    token?: string;
    user?: UserResponseDto;
    /**
     * Indica si se requiere cambio de contraseña
     */
    forcePasswordChange?: boolean | null;
}

