/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponse';


export interface AuthResponseDto { 
    token?: string;
    user?: UserResponseDto;
    forcePasswordChange?: boolean;
}

