/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyEntityDto } from './companyEntity';


export interface CompanyEmissionEntityDto { 
    id?: number;
    company?: CompanyEntityDto;
    year?: number;
    totalEmissions?: number;
    createdAt?: string;
}

