/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompanyCompensationResponseDto { 
    id?: number;
    companyId?: number;
    companyName?: string;
    year?: number;
    totalCompensations?: number;
    createdAt?: string;
}

