/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponse';
import { UserSummaryResponseDto } from './userSummaryResponse';


export interface CompanyResponseDto { 
    id?: number;
    name?: string;
    address?: string;
    admin?: UserResponseDto;
    users?: Array<UserSummaryResponseDto>;
    createdAt?: string;
}

