/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyCO2YearDTODto } from './companyCO2YearDTO';
import { UserSummaryResponseDto } from './userSummaryResponse';


export interface CompanyResponseDto { 
    id?: number;
    name?: string;
    address?: string;
    picture?: string;
    admin?: UserSummaryResponseDto;
    users?: Array<UserSummaryResponseDto>;
    createdAt?: string;
    co2?: Array<CompanyCO2YearDTODto>;
}

