/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyCompensationEntityDto } from './companyCompensationEntity';
import { LandEntityDto } from './landEntity';
import { UserEntityDto } from './userEntity';
import { CompanyEmissionEntityDto } from './companyEmissionEntity';


export interface CompanyEntityDto { 
    id?: number;
    name?: string;
    address?: string;
    admin?: UserEntityDto;
    users?: Array<UserEntityDto>;
    picture?: string;
    lands?: Array<LandEntityDto>;
    createdAt?: string;
    emissions?: Array<CompanyEmissionEntityDto>;
    compensations?: Array<CompanyCompensationEntityDto>;
}

