/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyCO2ValueDTODto } from './companyCO2ValueDTO';


export interface CompanyCO2YearDTODto { 
    year?: number;
    emissions?: CompanyCO2ValueDTODto;
    compensations?: CompanyCO2ValueDTODto;
}

