/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Compensaciones de CO2
 */
export interface CompanyCO2ValueDTODto { 
    /**
     * Total de CO2
     */
    total?: number;
}

