/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlannedPlantationKpiResponseDto } from './plannedPlantationKpiResponse';


export interface HomeDashboardKpiResponseDto { 
    plantedTrees?: number;
    plannedPlantations?: Array<PlannedPlantationKpiResponseDto>;
}

