/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateEntityDto } from './coordinateEntity';
import { CompanyEntityDto } from './companyEntity';
import { UserEntityDto } from './userEntity';


export interface LandEntityDto { 
    id?: number;
    name?: string;
    location?: string;
    area?: number;
    picture?: string;
    coordinates?: Array<CoordinateEntityDto>;
    companies?: Array<CompanyEntityDto>;
    users?: Array<UserEntityDto>;
    createdAt?: string;
    maxTrees?: number;
    isFull?: boolean;
}

