/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponse';
import { CompanyResponseDto } from './companyResponse';


export interface LandResponseDto { 
    id?: number;
    name?: string;
    location?: string;
    area?: number;
    picture?: string;
    users?: Array<UserResponseDto>;
    companies?: Array<CompanyResponseDto>;
    createdAt?: string;
}

