/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterUserRequestDto { 
    name?: string;
    surname?: string;
    secondSurname?: string;
    email?: string;
    password?: string;
    role?: string;
    companyId?: number;
}

