/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TreeRequestDto { 
    species?: string;
    co2Absorption?: number;
    plantedAt?: string;
    treeTypeId?: number;
    landId?: number;
    ownerUserId?: number;
    ownerCompanyId?: number;
    customName?: string;
}

