/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TreeTypeResponseDto } from './treeTypeResponse';
import { LandResponseDto } from './landResponse';


export interface TreeResponseDto { 
    id?: number;
    species?: string;
    co2Absorption?: number;
    plantedAt?: string;
    treeTypeId?: number;
    treeTypeName?: string;
    treeType?: TreeTypeResponseDto;
    landId?: number;
    landName?: string;
    land?: LandResponseDto;
    ownerUserId?: number;
    ownerUserName?: string;
    ownerCompanyId?: number;
    ownerCompanyName?: string;
    customName?: string;
}

