/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LandEntityDto } from './landEntity';


export interface TreeEntityDto {
  id?: number;
  land?: LandEntityDto;
  scientificName?: string;
  plantedAt?: string;
  co2AbsorptionAt20?: number;
  createdAt?: string;
}

