/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TreeTypeResponseDto { 
    id?: number;
    name?: string;
    description?: string;
    co2Absorption?: number;
    typicalHeight?: number;
    lifespanYears?: number;
    picture?: string;
}

