/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyResponseDto } from './companyResponse';


export interface UserResponseDto { 
    id?: number;
    name?: string;
    surname?: string;
    secondSurname?: string;
    email?: string;
    role?: string;
    emailVerified?: boolean;
    forcePasswordChange?: boolean;
    company?: CompanyResponseDto;
}

