/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyEntityDto } from './companyEntity';
import { LandEntityDto } from './landEntity';


export interface UserEntityDto { 
    id?: number;
    name?: string;
    surname?: string;
    secondSurname?: string;
    company?: CompanyEntityDto;
    email?: string;
    passwordHash?: string;
    role?: string;
    createdAt?: string;
    emailVerified?: boolean;
    forcePasswordChange?: boolean;
    uuid?: string;
    lands?: Array<LandEntityDto>;
}

