/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyEntityDto } from './companyEntity';
import { LandEntityDto } from './landEntity';


export interface UserEntityDto { 
    id?: number;
    name?: string;
    surname?: string;
    secondSurname?: string;
    picture?: string;
    company?: CompanyEntityDto;
    email?: string;
    passwordHash?: string;
    role?: UserEntityDto.RoleEnum;
    createdAt?: string;
    emailVerified?: boolean;
    forcePasswordChange?: boolean;
    uuid?: string;
    lands?: Array<LandEntityDto>;
}
export namespace UserEntityDto {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER',
        CompanyAdmin: 'COMPANY_ADMIN',
        CompanyUser: 'COMPANY_USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


